name: padaria_sustentavel_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter 
  cupertino_icons: ^1.0.8
  assorted_layout_widgets: ^9.0.1
  cached_network_image: ^3.3.1
  dotted_border: ^2.1.0
  flutter_svg: ^2.0.10+1
  fluttericon: ^2.0.0
  get: ^4.6.6
  pin_code_fields: ^8.0.1
  shimmer: ^3.0.0
  flutter_barcode_scanner: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true